### ISSUE TITLE
Plugin crashes with IntelliJ compiler

### ISSUE THREAD

**Issue by henrik242** [henrik242/kotlin-really-allopen#17]
Using Gradle 5.4.1, IntelliJ IDEA 2019.1 and Kotlin 1.3.31

[Quoting @fabianishere](https://github.com/fabianishere/kotlin-plugin-generated/issues/4#issuecomment-396531460): 

> This is caused by the fact that this compiler plugin is built against the compiler-embedable artifact which uses the org.jetbrains.kotlin.com.intellij.mock.MockProject class while the actual compiler artifact used by IntelliJ uses the com.intellij.mock.MockProject class instead.

> If we switch to the compiler artifact, the build will stop working for Gradle-only builds. A solution might be to write an IntelliJ plugin to load this plugin as seen in the Kotlin source (https://github.com/JetBrains/kotlin/tree/master/plugins/allopen). However, this requires some libraries which are not published as far as I know.

```
Error:Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin no.synth.reallyallopen.ReallyAllOpenRegistrar is not compatible with this version of compiler
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:182)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:413)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:259)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:124)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:436)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:102)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1023)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1065)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1022)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:434)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.AbstractMethodError: Receiver class no.synth.reallyallopen.ReallyAllOpenRegistrar does not define or inherit an implementation of the resolved method abstract registerProjectComponents(Lcom/intellij/mock/MockProject;Lorg/jetbrains/kotlin/config/CompilerConfiguration;)V of interface org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:174)
	... 33 more
```

Might be fixed by [creating an IDE plugin](https://github.com/fabianishere/kotlin-plugin-generated/issues/4#issuecomment-488595530), ref issue #6 

Related:
* https://github.com/fabianishere/kotlin-plugin-generated/issues/4
* https://youtrack.jetbrains.com/issue/KT-25596
* https://youtrack.jetbrains.com/issue/KT-24946
* https://github.com/JetBrains/kotlin-workshop/issues/12

**Comment by fabianishere** [comment]
Hi @henrik242,

I took another look at the issue and figured out how to build a custom IDE plugin for IntelliJ to fix it:
https://github.com/fabianishere/kotlin-plugin-generated/tree/master/plugin-idea

It works by searching for the Kotlin compiler plugin JAR that the Gradle plugin adds to the compiler options and replacing it with a similar JAR where the `org.jetbrains.kotlin.com.intellij` package is relocated to `com.intellij`.
Somewhat hacky solution, but this is the approach Jetbrains also uses for the `kotlinx-serialization` plugin.

**Comment by henrik242** [comment]
Thanks @fabianishere! I'll try replicating your work, since my plugin is kind of unusable (at least for me) without the IDE support.
